<a href="https://colab.research.google.com/github/grndnl/w266_final_project/blob/main/Exploratory_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data (1).csv to data (1).csv


In [ ]:
import io
import pandas as pd

df2 = pd.read_csv(io.BytesIO(uploaded['data (1).csv']))
df2

assembly_id                         assembly_name  \
0       290a9120f9f249a7a05cfe9c                           Lava Lamp 2   
1       1ffb81a71e5b402e966b9341                   Sample - Headphones   
2       d4fe04f0f5f84b52bd4f10e4                            Assem Test   
3       b33a147f86da49879455d286                     Sample Document 2   
4       9b3d6a97e8de4aa193b81000                            Coffee Mug   
...                          ...                                   ...   
456805  9ccf61f6077949dbd2c43331                     Untitled document   
456806  579b1fe6c67c43b68224f6bd                                  Rail   
456807  539900621bb6a2d2212a5774  Door lever child lock - old style_RH   
456808  534e3bf2bfb5d00571c53a39                     Untitled document   
456809  16e1dd3019350c773fb2707d                     Untitled document   

       assembly_description                                   part_names  
0                       NaN  ['Glass', 'Cap', 'Blob3', 'Blob1', 'Blob2']  
1                       NaN            ['Telescope hinge', 'Upper band']  
2                       NaN                                          NaN  
3                       NaN                                          NaN  
4                       NaN                                          NaN  
...                     ...                                          ...  
456805                  NaN                                          NaN  
456806                  NaN                                          NaN  
456807                  NaN                                          NaN  
456808                  NaN                                          NaN  
456809                  NaN                                          NaN  

[456810 rows x 4 columns]

In [ ]:
df3=df2['assembly_name'].unique().tolist()
len(df3)

292451

In [ ]:
from collections import Counter
c = Counter(df3)
type(c)

collections.Counter

In [ ]:
total_clean=df2.dropna()
total_clean

assembly_id                       assembly_name  \
374     2b2638f82b3946b1867f2d11                    #001 - Laddmodul   
472     3f3a389e9d5a4370b952bdce              #003 Experimentmoduler   
483     5bf4a74af99f405392406e40  HMB Hand Mold B (plain, composite)   
1387    442e41196093483f84a727a3                     x-axis carraige   
1905    df18fd6aa67f4654a5a1d99d                       00054-002-001   
...                          ...                                 ...   
453774  9a6b0df67cf086003676ab3d                        motion study   
454392  4f0884e0dc245ae45c41d303                             Pergola   
454969  48cfc8900b8ea6fc0a0a5374                        dwalt 780 xe   
455052  1e9907a1c9b9d48cf9af9cb2                           Saw Bench   
456120  5077b55485bcaeebea1d4fb7                         art project   

                                     assembly_description  \
374                 Utvecklingsmiljö för solarX laddmodul   
472                                  A4 - modul plattform   
483     HMB: A newly drawn (that is, not a copy of any...   
1387    First experience using OnShape. Existing geome...   
1905                         Cantilevered y-axis concept.   
...                                                   ...   
453774        Just a quick study of a patented technology   
454392  Pergola aus Holz. Siehe auch https://www.ulmer...   
454969  Crude Model of the Dewalt 78 Ex\n\nI've tried ...   
455052  This is a saw bench inspired from Christopher ...   
456120          https://www.thingiverse.com/thing:1324986   

                                               part_names  
374     ['DCDC regulator', 'Sbec', 'Laddregulator Stec...  
472     ['U-profil 9x10', 'Sliderplatta 30x4', 'A4 mod...  
483     ['9HMB1 Register (bottom)', '3HMB4 Mouthpiece ...  
1387    ['Bearing Block - LM8UU', 'Bearing LM8UU (x-ax...  
1905    ['x-axis beam - 40x40', 'E3D All Metal Hotend ...  
...                                                   ...  
453774                             ['lever 2', 'lever 1']  
454392  ['Tr\\X2\\00E4\\X0\\ger vorne', 'Balken oben 4...  
454969     ['Blade Mount', 'Blade', 'Front Locking Knob']  
455052  ['Leg Rear Right', 'Traverse Arri\\X2\\00E8\\X...  
456120  ['knife holder', '608 bearing', 'knife', '608 ...  

[688 rows x 4 columns]

In [ ]:
assembly_name_clean=df2.dropna(subset=['assembly_name'])
assembly_name_clean

assembly_id                         assembly_name  \
0       290a9120f9f249a7a05cfe9c                           Lava Lamp 2   
1       1ffb81a71e5b402e966b9341                   Sample - Headphones   
2       d4fe04f0f5f84b52bd4f10e4                            Assem Test   
3       b33a147f86da49879455d286                     Sample Document 2   
4       9b3d6a97e8de4aa193b81000                            Coffee Mug   
...                          ...                                   ...   
456805  9ccf61f6077949dbd2c43331                     Untitled document   
456806  579b1fe6c67c43b68224f6bd                                  Rail   
456807  539900621bb6a2d2212a5774  Door lever child lock - old style_RH   
456808  534e3bf2bfb5d00571c53a39                     Untitled document   
456809  16e1dd3019350c773fb2707d                     Untitled document   

       assembly_description                                   part_names  
0                       NaN  ['Glass', 'Cap', 'Blob3', 'Blob1', 'Blob2']  
1                       NaN            ['Telescope hinge', 'Upper band']  
2                       NaN                                          NaN  
3                       NaN                                          NaN  
4                       NaN                                          NaN  
...                     ...                                          ...  
456805                  NaN                                          NaN  
456806                  NaN                                          NaN  
456807                  NaN                                          NaN  
456808                  NaN                                          NaN  
456809                  NaN                                          NaN  

[456806 rows x 4 columns]

In [ ]:
assembly_name_clean=df2.dropna(subset=['assembly_name','assembly_description'])
assembly_name_clean

assembly_id  \
374     2b2638f82b3946b1867f2d11   
472     3f3a389e9d5a4370b952bdce   
483     5bf4a74af99f405392406e40   
790     6260c0e15525419fb05c1db8   
1387    442e41196093483f84a727a3   
...                          ...   
456120  5077b55485bcaeebea1d4fb7   
456193  05d4578c26200223ceeef992   
456194  f33f11ff8aae0bedc57097d4   
456632  7abcc7878568df101ac133c3   
456664  90e0863280a8dfc2e2da1f24   

                                            assembly_name  \
374                                      #001 - Laddmodul   
472                                #003 Experimentmoduler   
483                    HMB Hand Mold B (plain, composite)   
790                                               teste-1   
1387                                      x-axis carraige   
...                                                   ...   
456120                                        art project   
456193                                      balken 100x50   
456194  Toyota Hood Insulation Retainer Clip (2002 Toy...   
456632                                                New   
456664                                     Sundial Nozzle   

                                     assembly_description  \
374                 Utvecklingsmiljö för solarX laddmodul   
472                                  A4 - modul plattform   
483     HMB: A newly drawn (that is, not a copy of any...   
790             Cavalete de Apoio para montagem de teste.   
1387    First experience using OnShape. Existing geome...   
...                                                   ...   
456120          https://www.thingiverse.com/thing:1324986   
456193                                       Balken100x50   
456194  I didn't want to pay the dealership for a part...   
456632                                          Крепление   
456664  The Sundial Gnomon Mount and Water Nozzle is 1...   

                                               part_names  
374     ['DCDC regulator', 'Sbec', 'Laddregulator Stec...  
472     ['U-profil 9x10', 'Sliderplatta 30x4', 'A4 mod...  
483     ['9HMB1 Register (bottom)', '3HMB4 Mouthpiece ...  
790                                                   NaN  
1387    ['Bearing Block - LM8UU', 'Bearing LM8UU (x-ax...  
...                                                   ...  
456120  ['knife holder', '608 bearing', 'knife', '608 ...  
456193                                                NaN  
456194                                                NaN  
456632                                                NaN  
456664                                                NaN  

[2906 rows x 4 columns]

In [ ]:
assembly_name_clean=df2.dropna(subset=['part_names','assembly_description'])
assembly_name_clean

assembly_id                       assembly_name  \
374     2b2638f82b3946b1867f2d11                    #001 - Laddmodul   
472     3f3a389e9d5a4370b952bdce              #003 Experimentmoduler   
483     5bf4a74af99f405392406e40  HMB Hand Mold B (plain, composite)   
1387    442e41196093483f84a727a3                     x-axis carraige   
1905    df18fd6aa67f4654a5a1d99d                       00054-002-001   
...                          ...                                 ...   
453774  9a6b0df67cf086003676ab3d                        motion study   
454392  4f0884e0dc245ae45c41d303                             Pergola   
454969  48cfc8900b8ea6fc0a0a5374                        dwalt 780 xe   
455052  1e9907a1c9b9d48cf9af9cb2                           Saw Bench   
456120  5077b55485bcaeebea1d4fb7                         art project   

                                     assembly_description  \
374                 Utvecklingsmiljö för solarX laddmodul   
472                                  A4 - modul plattform   
483     HMB: A newly drawn (that is, not a copy of any...   
1387    First experience using OnShape. Existing geome...   
1905                         Cantilevered y-axis concept.   
...                                                   ...   
453774        Just a quick study of a patented technology   
454392  Pergola aus Holz. Siehe auch https://www.ulmer...   
454969  Crude Model of the Dewalt 78 Ex\n\nI've tried ...   
455052  This is a saw bench inspired from Christopher ...   
456120          https://www.thingiverse.com/thing:1324986   

                                               part_names  
374     ['DCDC regulator', 'Sbec', 'Laddregulator Stec...  
472     ['U-profil 9x10', 'Sliderplatta 30x4', 'A4 mod...  
483     ['9HMB1 Register (bottom)', '3HMB4 Mouthpiece ...  
1387    ['Bearing Block - LM8UU', 'Bearing LM8UU (x-ax...  
1905    ['x-axis beam - 40x40', 'E3D All Metal Hotend ...  
...                                                   ...  
453774                             ['lever 2', 'lever 1']  
454392  ['Tr\\X2\\00E4\\X0\\ger vorne', 'Balken oben 4...  
454969     ['Blade Mount', 'Blade', 'Front Locking Knob']  
455052  ['Leg Rear Right', 'Traverse Arri\\X2\\00E8\\X...  
456120  ['knife holder', '608 bearing', 'knife', '608 ...  

[688 rows x 4 columns]

# Part names > assembly id [Fabian]
# Description > assembly ID [Fabian]

In [ ]:
assembly_name_clean.part_names.shape

(688,)

In [ ]:
assembly_name_clean.part_names[0:1].shape

(1,)

In [ ]:
!pip install -q sentencepiece
!pip install -q transformers
from collections import Counter
import numpy as np
import tensorflow as tf
from tensorflow import keras
from transformers import T5Tokenizer, TFT5ForConditionalGeneration

     |████████████████████████████████| 1.3 MB 5.1 MB/s 
     |████████████████████████████████| 5.3 MB 5.5 MB/s 
     |████████████████████████████████| 7.6 MB 31.2 MB/s 
     |████████████████████████████████| 163 kB 58.6 MB/s 


In [ ]:
t5_model = TFT5ForConditionalGeneration.from_pretrained('t5-base')
t5_tokenizer = T5Tokenizer.from_pretrained('t5-base')

t5_model.summary()

Downloading:   0%|          | 0.00/1.20k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/892M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


Downloading:   0%|          | 0.00/792k [00:00<?, ?B/s]

Model: "tft5_for_conditional_generation"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 shared (TFSharedEmbeddings)  multiple                 24674304  
                                                                 
 encoder (TFT5MainLayer)     multiple                  84954240  
                                                                 
 decoder (TFT5MainLayer)     multiple                  113275008 
                                                                 
Total params: 222,903,552
Trainable params: 222,903,552
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/transformers/models/t5/tokenization_t5.py:174: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  FutureWarning,


I want to take the part names and predict a name of the assembly


In [ ]:
def process_string(string):
    string = string.lower()
    string = string.replace('_', ' ')
    string = string.replace('-', ' ')
    string = string.replace('[', ' ')
    string = string.replace(']', ' ')
    string = string.replace('(', ' ')
    string = string.replace(')', ' ')
    string = string.replace('?', ' ')
    string = string.replace("'", ' ')
    string = string.replace(",", ' ')
    return string

In [ ]:
PROMPT_SENTENCE = str(assembly_name_clean.part_names[0:1])
PROMPT_SENTENCE = process_string(PROMPT_SENTENCE)
PROMPT_SENTENCE


'374      dcdc regulator    sbec    laddregulator stec...\nname: part names  dtype: object'

In [ ]:


t5_input_text = PROMPT_SENTENCE
t5_inputs = t5_tokenizer([t5_input_text], return_tensors='tf')
t5_summary_ids = t5_model.generate(t5_inputs['input_ids'], 
                                   num_beams=9,
                                   no_repeat_ngram_size=2,
                                   num_return_sequences=1,
                                   min_length=1,
                                   max_length=3)
                             
print([t5_tokenizer.decode(g, skip_special_tokens=True, 
                           clean_up_tokenization_spaces=False) for g in t5_summary_ids])

['True']


I need to fine tunn the transformer or use a bert classifier being all the categories the names.

In [ ]:
t5_input_text= str(assembly_name_clean.assembly_name.unique)

In [ ]:
t5_input_text

'<bound method Series.unique of 374                         #001 - Laddmodul\n472                   #003 Experimentmoduler\n483       HMB Hand Mold B (plain, composite)\n1387                         x-axis carraige\n1905                           00054-002-001\n                         ...                \n453774                          motion study\n454392                               Pergola\n454969                          dwalt 780 xe\n455052                             Saw Bench\n456120                           art project\nName: assembly_name, Length: 688, dtype: object>'

In [ ]:
t5_inputs = t5_tokenizer([t5_input_text], return_tensors='tf')

In [ ]:
t5_inputs

{'input_ids': <tf.Tensor: shape=(1, 114), dtype=int32, numpy=
array([[    3,     2,  6115,  1573,  4531,     5,   202,  1495,    13,
          220,  4581,  1713, 17465,     3,    18,   325,    26,    26,
        22763,   314,  5865,  1713,  1206,   519,  1881,  4267,   297,
        22763,    49,   314,  4591,   454,  4633,  2263, 21338,   272,
           41, 18689,     6, 13723,    61,  1179,  4225,     3,   226,
           18,  8606,     7,   443,  7253,   397,   957,  3076,  6078,
         5062,    18,  1206, 19423,  4542,     3,   233,  3479,  4118,
         4581,  4644,   810,  3479,  4906,  4508,  1915,  7579,     9,
         3479,  3647,  3951,     3,    26,  5380,    17,   489,  2079,
            3,   226,    15,  3479,  1752,  5373, 19716, 21493,  3479,
         4241,  1755,   768,   516,  5570,    10,  7889,   834,  4350,
            6,   312,  1725,   189,    10,   431,  4060,     6,     3,
           26,  6137,    10,  3735,  3155,     1]], dtype=int32)>, 'attention_mask': <

In [ ]:
t5_inputs

{'input_ids': <tf.Tensor: shape=(1, 114), dtype=int32, numpy=
array([[    3,     2,  6115,  1573,  4531,     5,   202,  1495,    13,
          220,  4581,  1713, 17465,     3,    18,   325,    26,    26,
        22763,   314,  5865,  1713,  1206,   519,  1881,  4267,   297,
        22763,    49,   314,  4591,   454,  4633,  2263, 21338,   272,
           41, 18689,     6, 13723,    61,  1179,  4225,     3,   226,
           18,  8606,     7,   443,  7253,   397,   957,  3076,  6078,
         5062,    18,  1206, 19423,  4542,     3,   233,  3479,  4118,
         4581,  4644,   810,  3479,  4906,  4508,  1915,  7579,     9,
         3479,  3647,  3951,     3,    26,  5380,    17,   489,  2079,
            3,   226,    15,  3479,  1752,  5373, 19716, 21493,  3479,
         4241,  1755,   768,   516,  5570,    10,  7889,   834,  4350,
            6,   312,  1725,   189,    10,   431,  4060,     6,     3,
           26,  6137,    10,  3735,  3155,     1]], dtype=int32)>, 'attention_mask': <

ValueError: ignored